title: "Voltage Stabilizers"
theme: minima
author: Abhay Arsekar
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 Voltage stabilizers and what you should know about them

# social links
twitter_username: @abhayarsekar 
github_username:  @shyghost

show_excerpts: true # set to false to remove excerpts on the homepage
